# -*- coding: utf-8 -*-
#
# This file is part of Invenio Grobid
# Copyright (C) 2015 CERN
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 021111307, USA.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

notifications:
  email: false

sudo: false

services:
  - postgresql
  - redis

language: python

cache:
  - apt
  - pip

env:
  - REQUIREMENTS=lowest SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=devel SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - '2.7'

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inspirehep
  password:
    secure: n8dlsKbm+ogTpbVIgaZREiv9Ig+QRA8nn4M27LWlGjTvRL6qEtCB9U7qmzEAz6OAqLlpCw0xuosIx6kty/IiPK4RGDdksANBzTSdE8IRchAt3h0u+O9JOrrabRJWEtAjac8W5KaBNKHwH0vs1UB7GSXaQkZ6YIH9/F27OeALJPy/iFPq/UO5U6hpH2Y6uO075lWqF9tP6rJMZnrDhV7bRoJ1T9NPARPkhyBZ4brETkOj83DwmCh52rV9FSoixaXYHC/8vhAETbWucu/oT7OXYlCrRjItcbSk8MTxtb4vwXXuqhAe2xn1KsXbv1zt11Agu9emuoD/vxXPwvkDrfJUVvkWxFK7SN7G33H4w9L226PuKSjOpbzjwjCf6wmeYiOv5h27lM1/Swaryn+9mCk5YE7bcMzJbMllLQX15+jzw+j1Hgj/L6HXLPtEsY960wfCTT8cplBEe1TV1okbRudDkVI/BxCtzIKvNJeR5cT7/HXNNU60eD7br9cFiaurmXT61Y75zrrDxQ8pZRueZBTLt81S4JwmDzBmx9a9DP/4GcRW546spD3i1B/1ynRuvW2hsWWcRW9L1Y3QFrP9DNK1SErjU7jIOGKRqItemfk/AAWsdP5GDLyQ9FkiInKElC3fRqJ6LcKv4EV6yQDoULqZuYQMLn891a7m/qGHgIQFTQc=
  on:
    tags: true
    repo: inspirehep/invenio-grobid
